sudo: required
services:
  - docker

before_install:
  # decrypt service-account.json.enc
  - openssl aes-256-cbc -K $encrypted_069ebf1c588b_key -iv $encrypted_069ebf1c588b_iv -in service-account.json.enc -out ./app/service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
